# Pylops-distributed - Solvers

In this notebook we investigate the use of scipy solvers with distributed operators. 
We will also create a simple CG solver to compare the results and performance

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import skfmm
import dask.array as da
import pylops
import pylops_distributed

from scipy.sparse.linalg.interface import MatrixLinearOperator, aslinearoperator 
from scipy.sparse import csr_matrix, vstack
from scipy.linalg import lstsq, solve
from scipy.sparse.linalg import LinearOperator, cg, lsqr, gmres
from scipy.signal import convolve, filtfilt

In [2]:
client = pylops_distributed.utils.backend.dask(processes=False, threads_per_worker=2,
                                               n_workers=2)
client

<Client: scheduler='inproc://10.0.0.27/6800/1' processes=2 cores=4>

### CG for square systems

Let's just try out the solver with a matrix 

In [3]:
n = 10
x = np.ones(n)

A = np.random.randn(n, n)
A = np.dot(A.T, A)
print('eigs', np.linalg.eig(A)[0])

#A = MatrixLinearOperator(A)
Aop = aslinearoperator(A)

y = Aop.matvec(x)
xinv_sp = cg(Aop, y, maxiter=n)[0]
xinv = pylops_distributed.optimization.cg.cg(Aop, y, np.zeros_like(x), n)
print(xinv_sp)
print(xinv)

eigs [2.54225610e+01 1.57769992e+01 1.33041818e+01 1.08914148e+01
 8.36829500e+00 5.89361320e-03 1.75347759e-01 5.93957663e+00
 2.10726450e+00 4.13459248e+00]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


And with the LinearOperator

In [4]:
Ada = da.from_array(A, chunks=(n//2, n))
Adaop = pylops_distributed.MatrixMult(Ada, compute=(False, False))

y = Aop * np.ones(n)
yy = Adaop * da.ones(n, chunks=(n//2,))

xinv_sp = cg(Aop, yy, maxiter=n)[0]
xinv = pylops_distributed.optimization.cg.cg(Adaop, yy, da.zeros(n), n)
print(xinv_sp)
print(xinv)
print(xinv.compute())

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
dask.array<add, shape=(10,), dtype=float64, chunksize=(5,)>
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
%timeit -n 3 -r 1 cg(Aop, y, maxiter=n)[0]
%timeit -n 3 -r 1 pylops_distributed.optimization.cg.cg(Aop, y, da.zeros(n), n).compute()
%timeit -n 3 -r 1 pylops_distributed.optimization.cg.cg(Aop, y, da.zeros(n), n, compute=True)

2.08 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 3 loops each)
44.7 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 3 loops each)
24.6 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 3 loops each)


### CGLS for rectangular systems

In [6]:
n, m = 100, 6
x = np.ones(m)

A = np.random.randn(n, m)
Ada = da.from_array(A, chunks=(n//2, m), name='Aop')
Aop = pylops_distributed.MatrixMult(Ada, compute=(False, False))
y = Aop * da.ones(m, name='x')

xinv = pylops_distributed.optimization.cg.cgls(Aop, y, da.zeros(m, name='x0'), m)

In [7]:
y.visualize(rankdir="LR")
xinv.visualize(rankdir="LR")

In [8]:
print(xinv.compute())

[1. 1. 1. 1. 1. 1.]


In [9]:
%timeit -n 3 -r 1 pylops_distributed.optimization.cg.cgls(Aop, y, da.zeros(m), 20).compute()
%timeit -n 3 -r 1 pylops_distributed.optimization.cg.cgls(Aop, y, da.zeros(m), 20, compute=True)

1.77 s ± 0 ns per loop (mean ± std. dev. of 1 run, 3 loops each)
12.4 s ± 0 ns per loop (mean ± std. dev. of 1 run, 3 loops each)
