## ND-vs-1D behaviour for ambiguous operators

This notebooks has been used to verify the development of this PR: https://github.com/PyLops/pylops/pull/502.
        
Here, an operator is defined ambiguous is the output of either matvec or rmatvec is a 1d array (aka if dims or dimsd have len=1) . In this case pylops cannot tell whether a user would like a nd array or a 1d array when either rmatvec or matvec is performed on the 1d array from the other method.

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

import numpy as np
import pylops
import matplotlib.pyplot as plt

from scipy.sparse.linalg import lsqr as sp_lsqr
from pylops.optimization.basic import cgls, lsqr
from pylops.optimization.sparsity import fista

## Sum

### Sum: 2D -> 1D

In [2]:
# Adjoint returns 2D
S = pylops.Sum((10, 5), axis=-1)
print(S.dimsd, S.forceflat)
SH = S.H

x = np.ones(50)
y = S @ x
xadj = S.H @ y

print(y.shape)
print((S.rmatvec(y)).shape)
print((SH @ y).shape)
print(xadj.shape)

(10,) None
(10,)
(50,)
(10, 5)
(10, 5)


In [3]:
sp_lsqr(S, y), cgls(S, y), lsqr(S, y)
fista(S, y, niter=10, eps=1e-1)

(array([0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99]),
 2,
 array([4.9625, 4.9625]))

In [4]:
# Adjoint returns 1D by adding forceflat
S = pylops.Sum((10, 5), axis=-1, forceflat=True)
print(S.dimsd, S.forceflat)
SH = S.H

x = np.ones(50)
y = S @ x
xadj = S.H @ y

print(y.shape)
print((S.rmatvec(y)).shape)
print((SH @ y).shape)
print(xadj.shape)

(10,) True
(10,)
(50,)
(50,)
(50,)


In [5]:
sp_lsqr(S, y), cgls(S, y), lsqr(S, y)
fista(S, y, niter=10, eps=1e-1)

(array([0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99]),
 2,
 array([4.9625, 4.9625]))

### Sum: 3D -> 2D

No need for forceflatten, the operator is not ambiguos

In [6]:
S = pylops.Sum((10, 8, 5), axis=-1)
SH = S.H

x = np.ones(400)
y = S @ x
xadj = S.H @ y

print(y.shape)
print((S.rmatvec(y)).shape)
print((SH @ y).shape)
print(xadj.shape)

(80,)
(400,)
(400,)
(400,)


In [7]:
S = pylops.Sum((10, 8, 5), axis=-1, forceflat=False)
print(S.dimsd, S.forceflat)
SH = S.H

x = np.ones(400)
y = S @ x
xadj = S.H @ y

print(y.shape)
print((S.rmatvec(y)).shape)
print((SH @ y).shape)
print(xadj.shape)

(10, 8) None
(80,)
(400,)
(400,)
(400,)


In [8]:
sp_lsqr(S, y), cgls(S, y), lsqr(S, y)
fista(S, y, niter=10, eps=1e-1)

(array([0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99,
        0.99, 0.99, 0.99, 0.99, 0.99, 

## Bilinear

### Bilinear: 2D -> 1D

In [9]:
# 2D array - Bilinear ambiguous
nz, nx = 50, 40

nsamples = 200
iava = np.vstack(
    (np.random.uniform(0, nz - 1, nsamples), np.random.uniform(0, nx - 1, nsamples))
)

B = pylops.signalprocessing.Bilinear(iava, (nz, nx))
x = np.arange(nz*nx).reshape(nz, nx)
y = B * x
xadj = B.H * y

In [10]:
B.dimsd, y.shape, xadj.shape, #fista(Bop, y, niter=10, eps=1e-1)

((200,), (200,), (50, 40))

In [11]:
# 2D array - Bilinear ambiguous (forceflat to have 1d vectors)
nz, nx = 50, 40

nsamples = 200
iava = np.vstack(
    (np.random.uniform(0, nz - 1, nsamples), np.random.uniform(0, nx - 1, nsamples))
)

B = pylops.signalprocessing.Bilinear(iava, (nz, nx), forceflat=True)
x = np.arange(nz*nx).reshape(nz, nx)
y = B * x
xadj = B.H * y

In [12]:
B.dimsd, y.shape, xadj.shape, fista(B, y, niter=100, eps=1e-10)

((200,),
 (200,),
 (2000,),
 (array([   0.        ,    0.        ,    0.        , ..., 2750.67307624,
            0.        ,    0.        ]),
  100,
  array([4.89576169e+07, 2.04237564e+07, 7.24562902e+06, 2.14386724e+06,
         5.18177237e+05, 1.30386103e+05, 8.19103975e+04, 8.03020584e+04,
         6.42364151e+04, 4.04320816e+04, 2.20524268e+04, 1.29585251e+04,
         1.00836363e+04, 9.21472082e+03, 8.08290637e+03, 6.40191679e+03,
         4.69366557e+03, 3.37781932e+03, 2.51894946e+03, 1.96955922e+03,
         1.56739368e+03, 1.22714082e+03, 9.32371372e+02, 6.92320244e+02,
         5.11003583e+02, 3.80213157e+02, 2.86303659e+02, 2.17976481e+02,
         1.69040416e+02, 1.36799881e+02, 1.19267570e+02, 1.13546779e+02,
         1.15841962e+02, 1.22336128e+02, 1.30018347e+02, 1.37006484e+02,
         1.42402879e+02, 1.45941173e+02, 1.47648157e+02, 1.47616659e+02,
         1.45891716e+02, 1.42442980e+02, 1.37199093e+02, 1.30120430e+02,
         1.21278761e+02, 1.10909210e+02, 9.9411

### Bilinear: 3D -> 2D

In [13]:
# 3D array - bilinear not ambiguous
nz, nx, nt = 50, 40, 10

nsamples = 200
iava = np.vstack(
    (np.random.uniform(0, nz - 1, nsamples), np.random.uniform(0, nx - 1, nsamples))
)

B = pylops.signalprocessing.Bilinear(iava, (nz, nx, nt))#, forceflat=True)
x = np.arange(nz*nx*nt).reshape(nz, nx, nt)
y = B * x
xadj = B.H * y

In [14]:
y.shape, xadj.shape, fista(B, y.ravel(), niter=100, eps=1e-10)

((200, 10),
 (50, 40, 10),
 (array([0., 0., 0., ..., 0., 0., 0.]),
  100,
  array([3.98890113e+10, 1.58975605e+10, 5.47749002e+09, 1.57168876e+09,
         3.77655381e+08, 1.15226048e+08, 8.33261661e+07, 7.32098714e+07,
         5.34490838e+07, 3.34845937e+07, 2.05694936e+07, 1.44901021e+07,
         1.20519745e+07, 1.06909779e+07, 9.36741423e+06, 7.99635462e+06,
         6.74129044e+06, 5.68333607e+06, 4.79738691e+06, 4.02666082e+06,
         3.33444433e+06, 2.71294509e+06, 2.17021831e+06, 1.71505645e+06,
         1.34835346e+06, 1.06177131e+06, 8.41224517e+05, 6.71804146e+05,
         5.41409219e+05, 4.41944171e+05, 3.68521796e+05, 3.17879252e+05,
         2.87058572e+05, 2.72786024e+05, 2.71445025e+05, 2.79326238e+05,
         2.92899031e+05, 3.08998962e+05, 3.24933004e+05, 3.38535931e+05,
         3.48199440e+05, 3.52877790e+05, 3.52066438e+05, 3.45751383e+05,
         3.34330793e+05, 3.18514219e+05, 2.99208633e+05, 2.77404352e+05,
         2.54075699e+05, 2.30109043e+05, 2.0626431

## VStack

In [15]:
# VStack with Sum (the output of adjoint is a ndarray if not forced)
nz, nx, nt = 20, 10, 5
Szop = pylops.Sum((nz, nx, nt), axis=0)
Sxop = pylops.Sum((nz, nx, nt), axis=1)
Szop1 = Szop.H @ Szop
Sxop1 = Sxop.H @ Sxop

Vop = pylops.VStack([Sxop1, Szop1])
Vop1 = pylops.VStack([Sxop1, Szop1], forceflat=True)
print(Vop.forceflat)

print((Vop @ np.ones(Vop.dims)).shape, (Vop1 @ np.ones(Vop.dims)).shape)
print((Vop.H @ np.ones(Vop.dimsd)).shape, (Vop1.H @ np.ones(Vop.dimsd)).shape)

print((Vop @ np.ones(Vop.shape[1])).shape, (Vop1 @ np.ones(Vop.shape[1])).shape)
print((Vop.H @ np.ones(Vop.shape[0])).shape, (Vop1.H @ np.ones(Vop.shape[0])).shape)

None
(2000,) (2000,)
(20, 10, 5) (1000,)
(2000,) (2000,)
(20, 10, 5) (1000,)


In [16]:
# VStack with Diagonal (the output of adjoint is a ndarray if not forced)
D1 = pylops.Diagonal(np.ones(10), dims=(20, 10), axis=-1)
D2 = pylops.Diagonal(np.arange(10), dims=(20, 10), axis=-1)

Vop = pylops.VStack([D1, D2])
Vop1 = pylops.VStack([D1, D2], forceflat=True)
print(Vop.forceflat)

print((Vop @ np.ones(Vop.dims)).shape, (Vop1 @ np.ones(Vop.dims)).shape)
print((Vop.H @ np.ones(Vop.dimsd)).shape, (Vop1.H @ np.ones(Vop.dimsd)).shape)

print((Vop @ np.ones(Vop.shape[1])).shape, (Vop1 @ np.ones(Vop.shape[1])).shape)
print((Vop.H @ np.ones(Vop.shape[0])).shape, (Vop1.H @ np.ones(Vop.shape[0])).shape)

None
(400,) (400,)
(20, 10) (200,)
(400,) (400,)
(20, 10) (200,)


In [17]:
# VStack with Diagonal (the input dims of two operators is different, so VStack is return always flat arrays)
D1 = pylops.Diagonal(np.ones(10), dims=(20, 10), axis=-1)
D2 = pylops.Diagonal(np.arange(20), dims=(10, 20), axis=-1)

Vop = pylops.VStack([D1, D2])
Vop1 = pylops.VStack([D1, D2], forceflat=True)
print(Vop.forceflat)

print((Vop @ np.ones(Vop.dims)).shape, (Vop1 @ np.ones(Vop.dims)).shape)
print((Vop.H @ np.ones(Vop.dimsd)).shape, (Vop1.H @ np.ones(Vop.dimsd)).shape)

print((Vop @ np.ones(Vop.shape[1])).shape, (Vop1 @ np.ones(Vop.shape[1])).shape)
print((Vop.H @ np.ones(Vop.shape[0])).shape, (Vop1.H @ np.ones(Vop.shape[0])).shape)

True
(400,) (400,)
(200,) (200,)
(400,) (400,)
(200,) (200,)


In [18]:
# VStack with Diagonal and operator in front (the output of adjoint is a ndarray if not forced)
D1 = pylops.Diagonal(np.ones(10), dims=(20, 10), axis=-1)
D2 = pylops.Diagonal(np.arange(10), dims=(20, 10), axis=-1)
D = pylops.MatrixMult(np.ones((10, 10)), otherdims=(20),)

Vop = pylops.VStack([D1, D2]) @ D
Vop1 = pylops.VStack([D1, D2], forceflat=True) @ D
print(Vop.forceflat, Vop1.forceflat)

print((Vop @ np.ones(Vop.dims)).shape, (Vop1 @ np.ones(Vop.dims)).shape)
print((Vop.H @ np.ones(Vop.dimsd)).shape, (Vop1.H @ np.ones(Vop.dimsd)).shape)

print((Vop @ np.ones(Vop.shape[1])).shape, (Vop1 @ np.ones(Vop.shape[1])).shape)
print((Vop.H @ np.ones(Vop.shape[0])).shape, (Vop1.H @ np.ones(Vop.shape[0])).shape)

None True
(400,) (400,)
(10, 20) (200,)
(400,) (400,)
(10, 20) (200,)


## HStack

In [19]:
# HStack with Diagonal (the output of forward is a ndarray if not forced)
D1 = pylops.Diagonal(np.ones(10), dims=(20, 10), axis=-1)
D2 = pylops.Diagonal(np.arange(10), dims=(20, 10), axis=-1)

Hop = pylops.HStack([D1, D2])
Hop1 = pylops.HStack([D1, D2], forceflat=True)

print((Hop @ np.ones(Hop.dims)).shape, (Hop1 @ np.ones(Hop.dims)).shape)
print((Hop.H @ np.ones(Hop.dimsd)).shape, (Hop1.H @ np.ones(Hop.dimsd)).shape)

print((Hop @ np.ones(Hop.shape[1])).shape, (Hop1 @ np.ones(Hop.shape[1])).shape)
print((Hop.H @ np.ones(Hop.shape[0])).shape, (Hop1.H @ np.ones(Hop.shape[0])).shape)

(20, 10) (200,)
(400,) (400,)
(20, 10) (200,)
(400,) (400,)


In [20]:
# HStack with Diagonal (the output dimsd of two operators is different, so HStack is return always flat arrays)
D1 = pylops.Diagonal(np.ones(10), dims=(20, 10), axis=-1)
D2 = pylops.Diagonal(np.arange(20), dims=(10, 20), axis=-1)

Hop = pylops.HStack([D1, D2])
Hop1 = pylops.HStack([D1, D2], forceflat=True)
print(Hop.forceflat)

print((Hop @ np.ones(Hop.dims)).shape, (Hop1 @ np.ones(Hop.dims)).shape)
print((Hop.H @ np.ones(Hop.dimsd)).shape, (Hop1.H @ np.ones(Hop.dimsd)).shape)

print((Hop @ np.ones(Hop.shape[1])).shape, (Hop1 @ np.ones(Hop.shape[1])).shape)
print((Hop.H @ np.ones(Hop.shape[0])).shape, (Hop1.H @ np.ones(Hop.shape[0])).shape)

True
(200,) (200,)
(400,) (400,)
(200,) (200,)
(400,) (400,)


In [21]:
# HStack with Diagonal and operator in end (the output of forward is a ndarray if not forced)
D1 = pylops.Diagonal(np.ones(10), dims=(20, 10), axis=-1)
D2 = pylops.Diagonal(np.arange(10), dims=(20, 10), axis=-1)
D = pylops.MatrixMult(np.ones((10, 10)), otherdims=(20),)

Hop = D @ pylops.HStack([D1, D2])
Hop1 = D @ pylops.HStack([D1, D2], forceflat=True)
print(Hop.forceflat)

print((Hop @ np.ones(Hop.dims)).shape, (Hop1 @ np.ones(Hop.dims)).shape)
print((Hop.H @ np.ones(Hop.dimsd)).shape, (Hop1.H @ np.ones(Hop.dimsd)).shape)

print((Hop @ np.ones(Hop.shape[1])).shape, (Hop1 @ np.ones(Hop.shape[1])).shape)
print((Hop.H @ np.ones(Hop.shape[0])).shape, (Hop1.H @ np.ones(Hop.shape[0])).shape)

None
(10, 20) (200,)
(400,) (400,)
(10, 20) (200,)
(400,) (400,)


## Block

In [22]:
Bop = pylops.Block([[pylops.Identity(5), pylops.Zero(5),       pylops.Zero(5)],
                    [pylops.Zero(5),     2*pylops.Identity(5), pylops.Zero(5)],
                    [pylops.Zero(5),     pylops.Zero(5),       -1*pylops.Identity(5)]])
Bop1 = pylops.Block([[pylops.Identity(5), pylops.Zero(5),       pylops.Zero(5)],
                    [pylops.Zero(5),     2*pylops.Identity(5), pylops.Zero(5)],
                    [pylops.Zero(5),     pylops.Zero(5),       -1*pylops.Identity(5)]], 
                    forceflat=True)

print(Bop, Bop.dims, Bop.dimsd)

print((Bop @ np.ones(Bop.dims)).shape, (Bop1 @ np.ones(Bop.dims)).shape)
print((Bop.H @ np.ones(Bop.dimsd)).shape, (Bop1.H @ np.ones(Bop.dimsd)).shape)

print((Bop @ np.ones(Bop.shape[1])).shape, (Bop1 @ np.ones(Bop.shape[1])).shape)
print((Bop.H @ np.ones(Bop.shape[0])).shape, (Bop1.H @ np.ones(Bop.shape[0])).shape)

<15x15 Block with dtype=float64> (15,) (15,)
(15,) (15,)
(15,) (15,)
(15,) (15,)
(15,) (15,)


In [23]:
Dop = pylops.Diagonal(np.ones(10), dims=(20, 10), axis=-1)
Mop = pylops.MatrixMult(np.ones((20, 20)), otherdims=(10),)

Bop = pylops.Block([[Dop, Mop, Dop],
                    [Mop, Dop, Dop],
                    [Dop, Dop, Mop]])
Bop1 = pylops.Block([[Dop, Mop, Dop],
                    [Mop, Dop, Dop],
                    [Dop, Dop, Mop]],
                     forceflat=True)
print(Bop, Bop.dims, Bop.dimsd)

print((Bop @ np.ones(Bop.dims)).shape, (Bop1 @ np.ones(Bop.dims)).shape)
print((Bop.H @ np.ones(Bop.dimsd)).shape, (Bop1.H @ np.ones(Bop.dimsd)).shape)

print((Bop @ np.ones(Bop.shape[1])).shape, (Bop1 @ np.ones(Bop.shape[1])).shape)
print((Bop.H @ np.ones(Bop.shape[0])).shape, (Bop1.H @ np.ones(Bop.shape[0])).shape)

<600x600 Block with dtype=float64> (600,) (600,)
(600,) (600,)
(600,) (600,)
(600,) (600,)
(600,) (600,)


## BlockDiag

In [24]:
# BlockDiag with Diagonal (same size for input and output - ndarrays)
D1 = pylops.Diagonal(np.ones(10), dims=(20, 10), axis=-1)
D2 = pylops.Diagonal(np.arange(10), dims=(20, 10), axis=-1)
D = pylops.MatrixMult(np.ones((10, 20)), otherdims=(20),)

Bop = pylops.BlockDiag([D1, D2])
Bop1 = pylops.BlockDiag([D1, D2], forceflat=True)
print(Bop.forceflat)

print((Bop @ np.ones(Bop.dims)).shape, (Bop1 @ np.ones(Bop.dims)).shape)
print((Bop.H @ np.ones(Bop.dimsd)).shape, (Bop1.H @ np.ones(Bop.dimsd)).shape)

(2, 20, 10) (2, 20, 10)
(2, 20, 10) (2, 20, 10)
None
(2, 20, 10) (400,)
(2, 20, 10) (400,)


In [25]:
# BlockDiag with Diagonal (different size for input and output - forced 1darrays)
D1 = pylops.Diagonal(np.ones(10), dims=(20, 10), axis=-1)
D2 = pylops.Diagonal(np.arange(20), dims=(10, 20), axis=-1)

Bop = pylops.BlockDiag([D1, D2])
print(Bop.forceflat)

print((Bop @ np.ones(Bop.shape[1])).shape)
print((Bop.H @ np.ones(Bop.shape[0])).shape)

(400,) (400,)
True
(400,)
(400,)


In [26]:
# BlockDiag with Diagonal and operator in front 
D1 = pylops.Diagonal(np.ones(10), dims=(20, 10), axis=-1)
D2 = pylops.Diagonal(np.arange(10), dims=(20, 10), axis=-1)
D = pylops.MatrixMult(np.ones((20, 10)), otherdims=(20),)

Bop = pylops.BlockDiag([D1, D2]) @ D
Bop1 = pylops.BlockDiag([D1, D2], forceflat=True) @ D
print(Bop.forceflat)

print((Bop @ np.ones(Bop.dims)).shape, (Bop1 @ np.ones(Bop.dims)).shape)
print((Bop.H @ np.ones(Bop.dimsd)).shape, (Bop1.H @ np.ones(Bop.dimsd)).shape)

print((Bop @ np.ones(Bop.shape[1])).shape, (Bop1 @ np.ones(Bop.shape[1])).shape)
print((Bop.H @ np.ones(Bop.shape[0])).shape, (Bop1.H @ np.ones(Bop.shape[0])).shape)

(2, 20, 10) (2, 20, 10)
(2, 20, 10) (2, 20, 10)
None
(2, 20, 10) (400,)
(10, 20) (200,)
(400,) (400,)
(200,) (200,)


In [27]:
# BlockDiag with Diagonal and operator in front (different size for input and output - forced 1darrays)
D1 = pylops.Diagonal(np.ones(10), dims=(20, 10), axis=-1)
D2 = pylops.Diagonal(np.arange(20), dims=(10, 20), axis=-1)
D = pylops.MatrixMult(np.ones((20, 10)), otherdims=(20),)

Bop = pylops.BlockDiag([D1, D2]) @ D
Bop1 = pylops.BlockDiag([D1, D2], forceflat=True) @ D
print(Bop.forceflat)

print((Bop @ np.ones(Bop.dims)).shape, (Bop1 @ np.ones(Bop.dims)).shape)
print((Bop.H @ np.ones(Bop.dimsd)).shape, (Bop1.H @ np.ones(Bop.dimsd)).shape)

print((Bop @ np.ones(Bop.shape[1])).shape, (Bop1 @ np.ones(Bop.shape[1])).shape)
print((Bop.H @ np.ones(Bop.shape[0])).shape, (Bop1.H @ np.ones(Bop.shape[0])).shape)

(400,) (400,)
(400,) (400,)
True
(400,) (400,)
(200,) (200,)
(400,) (400,)
(200,) (200,)


## MatrixMult

In [28]:
M = pylops.MatrixMult(np.ones((30, 25)))
M1 = pylops.MatrixMult(np.ones((30, 25)), forceflat=True)
F = pylops.signalprocessing.FFT2D((5, 5))
Op = M @ F
Op1 = M1 @ F
print(Op.forceflat)
print(Op1.forceflat)

print((Op @ np.ones(Op.dims)).shape, (Op @ np.ones(Op.shape[1])).shape)
print((Op.H @ np.ones(Op.dimsd)).shape, (Op.H @ np.ones(Op.shape[0])).shape)

print((Op1 @ np.ones(Op.dims)).shape, (Op1 @ np.ones(Op.shape[1])).shape)
print((Op1.H @ np.ones(Op.dimsd)).shape, (Op1.H @ np.ones(Op.shape[0])).shape)

None
True
(30,) (30,)
(5, 5) (5, 5)
(30,) (30,)
(25,) (25,)


## Identity

In [29]:
I = pylops.Identity(25)
I1 = pylops.Identity(25, forceflat=True)
F = pylops.signalprocessing.FFT2D((5, 5))
print(I.forceflat, I1.forceflat)
Op = I @ F
Op1 = I1 @ F

print((Op @ np.ones(Op.shape[1])).shape, (Op1 @ np.ones(Op.shape[1])).shape)
print((Op.H @ np.ones(Op.shape[0])).shape, (Op1.H @ np.ones(Op.shape[0])).shape)

print((Op @ np.ones(Op.dims)).shape, (Op1 @ np.ones(Op.dims)).shape)
print((Op.H @ np.ones(Op.dimsd)).shape, (Op1.H @ np.ones(Op.dimsd)).shape)

None True
(25,) (25,)
(5, 5) (25,)
(25,) (25,)
(5, 5) (25,)


In [30]:
I = pylops.Identity((3, 5), (5, 5))
I1 = pylops.Identity((3, 5), (5, 5), forceflat=True)
F = pylops.signalprocessing.FFT2D((5, 5))
print(I.forceflat, I1.forceflat)
Op = I @ F
Op1 = I1 @ F

print((Op @ np.ones(Op.shape[1])).shape, (Op1 @ np.ones(Op.shape[1])).shape)
print((Op.H @ np.ones(Op.shape[0])).shape, (Op1.H @ np.ones(Op.shape[0])).shape)

print((Op @ np.ones(Op.dims)).shape, (Op1 @ np.ones(Op.dims)).shape)
print((Op.H @ np.ones(Op.dimsd)).shape, (Op1.H @ np.ones(Op.dimsd)).shape)

None True
(15,) (15,)
(25,) (25,)
(3, 5) (15,)
(5, 5) (25,)


## Zero

In [61]:
Z = pylops.Zero((3, 5), (5, 5))
Z1 = pylops.Zero((3, 5), (5, 5), forceflat=True)

print((Z @ np.ones(Z.shape[1])).shape, (Z1 @ np.ones(Z.shape[1])).shape)
print((Z.H @ np.ones(Z.shape[0])).shape, (Z1.H @ np.ones(Z.shape[0])).shape)

print((Z @ np.ones(Z.dims)).shape, (Z1 @ np.ones(Z.dims)).shape)
print((Z.H @ np.ones(Z.dimsd)).shape, (Z1.H @ np.ones(Z.dimsd)).shape)

(15,) (15,)
(25,) (25,)
(3, 5) (15,)
(5, 5) (25,)


In [ ]:
Z = pylops.Zero(25, 10)
Z1 = pylops.Zero(25, 10, forceflat=True)

print((Z @ np.ones(Z.shape[1])).shape, (Z1 @ np.ones(Z.shape[1])).shape)
print((Z.H @ np.ones(Z.shape[0])).shape, (Z1.H @ np.ones(Z.shape[0])).shape)

print((Z @ np.ones(Z.dims)).shape, (Z1 @ np.ones(Z.dims)).shape)
print((Z.H @ np.ones(Z.dimsd)).shape, (Z1.H @ np.ones(Z.dimsd)).shape)

## Inconsistent use of forceflat for two operators

In [31]:
S = pylops.Sum((nz, nx), axis=-1, forceflat=False)
B = pylops.signalprocessing.Bilinear(iava, (nz, nx), forceflat=True)
BH = B.H 

print(BH.forceflat, S.forceflat)
print(S @ B.H, B @ S.H)

True False


ValueError: the two operators have contrasting forceflat None-True